spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
    alicloud:
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        appcode: ab
        sign: 1
        skin: 20
  zipkin:
    base-url: http://120.79.158.181:9411/

    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

server:
  port: 8010

logging:
  level:
    com.ysy.tmall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

