spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
    alicloud:
      sms:
        host: https://feginesms.market.alicloudapi.com
        path: /codeNotice
        appcode: ab
        sign: 1
        skin: 20


server:
  port: 8010
