spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
  application:
    name: tmall-search
  thymeleaf:
    cache: false
  redis:
    host: 129.211.93.117
  session:
    store-type: redis

server:
  port: 8011
logging:
  level:
    com.ysy.tmall: debug


