spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tmall_pms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117:1111
        namespace: d1552e2b-fa42-454e-8d36-d2163db24063
  application:
    name: tmall-product


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 8002
logging:
  level:
    com.ysy.tmall: debug


