spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  application:
    name: tmall-auth-server
  thymeleaf:
    cache: false
  redis:
    host: 129.211.93.117
  session:
    store-type: redis



server:
  port: 8015
  servlet:
    session:
      timeout: 30m


logging:
  level:
    com.ysy.tmall: debug


