spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
  application:
    name: tmall-auth-server
  thymeleaf:
    cache: false


server:
  port: 8015
logging:
  level:
    com.ysy.tmall: debug


