spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  redis:
    host: 129.211.93.117 # 如果是 线上 购物车redis 和 缓存redis 不共用  目前 测试共用
  session:
    store-type: redis
  thymeleaf:
    cache: false
  zipkin:
    base-url: http://120.79.158.181:9411/

    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

server:
  port: 8016
logging:
  level:
    com.ysy.tmall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
#线程池自定义配置
ysymall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10
