spring:
  datasource:
    # 当前数据源操作类型
#    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tmall_oms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    alibaba:
      seata:
        # 自定义事务组名称需要与seata-server中的对应
        tx-service-group: ysy_tx_group
    nacos:
      discovery:
        server-addr: 129.211.93.117
  application:
    name: tmall-order
  rabbitmq:
    host: 120.79.158.181
    port: 5672
    virtual-host: /
    #开启发送端确认
    publisher-confirm-type: correlated
    #开启发送端抵达队列确认
    publisher-returns: true
    #只要抵达队列，以异步方式优先回调returnconfirm
    template:
      mandatory: true
    #手动确认消息处理
    listener:
      simple:
        acknowledge-mode: manual
  thymeleaf:
    cache: false

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 8003
logging:
  level:
    com.ysy.tmall: debug

#线程池自定义配置
ysymall:
  thread:
    core-size: 20
    max-size: 200
    keep-alive-time: 10

