spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/tmall_sms?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117:1111
        namespace: 09066cec-e453-46b6-811e-1629b0a2e8d2
  application:
    name: tmall-order


mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto
      logic-delete-value: 1
      logic-not-delete-value: 0


server:
  port: 8003
logging:
  level:
    com.ysy.tmall: debug


