spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
    sentinel:
      transport:
        dashboard: localhost:8080
        port: 8719
  application:
    name: tmall-seckill
  redis:
    host: 129.211.93.117
  session:
    store-type: redis
  rabbitmq:
    host: 120.79.158.181
    port: 5672
    virtual-host: /
    #开启发送端确认
    publisher-confirm-type: correlated
    #开启发送端抵达队列确认
    publisher-returns: true
    #只要抵达队列，以异步方式优先回调returnconfirm
    template:
      mandatory: true
    #手动确认消息处理
    listener:
      simple:
        acknowledge-mode: manual

  thymeleaf:
    cache: false
  zipkin:
    base-url: http://120.79.158.181:9411/

    discovery-client-enabled: false
    sender:
      type: web

  sleuth:
    sampler:
      probability: 1

#   不加会产生死锁
    redis:
      enabled: false

server:
  port: 8046
logging:
  level:
    com.ysy.tmall: debug
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug

