spring:
  cloud:
    nacos:
      discovery:
        server-addr: 129.211.93.117
  application:
    name: tmall-seckill
  redis:
    host: 129.211.93.117


server:
  port: 8046
logging:
  level:
    com.ysy.tmall: debug


